CREATE TABLE IF NOT EXISTS site (
  site_id       BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  site_uuid     VARCHAR(40) NOT NULL,
  url           VARCHAR(256) NOT NULL,
  created_at    TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at    TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=UTF8;

CREATE TABLE IF NOT EXISTS question (
    question_id     BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    site_id         BIGINT NOT NULL,
    question        VARCHAR(250) NOT NULL,
    question_type   VARCHAR(64) NOT NULL,
    created_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=UTF8;

CREATE TABLE IF NOT EXISTS question_answer (
    question_answer_id  BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    question_id         BIGINT NOT NULL,
    answer              VARCHAR(250) NOT NULL,
    is_correct_answer   BOOLEAN NOT NULL DEFAULT false,
    created_at          TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=UTF8;

CREATE TABLE IF NOT EXISTS question_answer_option (
    id                  BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    question_answer_id  BIGINT NOT NULL,
    option_text         VARCHAR(250) NOT NULL,
    created_at          TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=UTF8;